name: Weather Data Service

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Install AWS Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Package API
        run: |
          dotnet lambda package --project-location ./src/WeatherForecast.Api \
          --configuration Release \
          --framework net8.0 \
          --output-package artifacts/api.zip

      - name: Package API
        run: |
          dotnet lambda package --project-location ./src/WeatherForecast.Service \
          --configuration Release \
          --framework net8.0 \
          --output-package artifacts/service.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: "ap-southeast-2"

      - name: CDK Deploy
        run: cdk deploy --all --require-approval never
